# SwiftLint Configuration
included:
  - app-ios/
  - scripts/
excluded:
  - Pods
  - .build
  - scripts/.build
  - Sources

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - force_unwrapping
  - private_outlet
  - redundant_nil_coalescing
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call

disabled_rules:
  - trailing_whitespace

line_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

trailing_comma:
  mandatory_comma: true
  mandatory_last: true

indentation_width:
  warning: 2
  error: 2